# Generated by Django 3.1.3 on 2020-12-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('cover', models.ImageField(upload_to='covers', verbose_name='Carátula')),
                ('cover_path', models.CharField(max_length=200, verbose_name='Carátula')),
                ('release', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('generos', models.ManyToManyField(to='main.Genero')),
            ],
        ),
    ]
