# Generated by Django 3.1.2 on 2020-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='description',
            field=models.CharField(default='No description', max_length=500, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
