# Generated by Django 3.1.3 on 2021-01-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_puntuacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='ropa',
            new_name='juego',
        ),
    ]
